### ISSUE TITLE
epic(contracts-controller):  feat: MsgServer migration + better owner abstraction 

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/nibiru-wasm#103]
## New Objective [2024-04-22]

https://github.com/NibiruChain/nibiru-wasm/issues/103#issuecomment-2820147597

<details>
<summary>[Original Description from 2023]</summary>

- [ ] Migrate `core-controller` contract to use `cw_ownable`
- [ ] Implement MsgServer methods on the admin to call as `CosmosMsg::Stargate` in the contract
- [ ] Use the `operator_perms.Action` abstraction from the ["core-shifter" contract](https://github.com/NibiruChain/cw-nibiru/blob/0039bf48f549bc69faffda7592415bb533cc3568/contracts/core-shifter/src/msgs.rs)
- [ ] Update contract to use MsgServer methods  

</details>

**Comment by Unique-Divine** [comment]
Instead, remove this from the repo since the contracts were moved out as https://github.com/NibiruChain/sai-perps
