### ISSUE TITLE
epic(nusd/design): Complete design of NUSD with multi-collateral support for initial audit.

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/nibiru-wasm#95]
- [ ] design: Propose variation internally based on stableswap logic
- [ ] design: Propose variation based on oracles
- [ ] design: Finalize first production design for the smart contract audit

**Comment by Unique-Divine** [comment]
Not needed
